
[workspace]
resolver= "2"
members = [
	"llmd",
	"llm-bias",
	"llm-ui"
]

[workspace.dependencies]
llm = { git = "https://github.com/rustformers/llm.git" }

[patch.crates-io]
llm-bias = { path = "./llm-bias" }
llmd = { path = "./llmd" }